<a href="https://colab.research.google.com/github/Chanakarn06/multivariate-/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Function



```
def function_name(_Input_):
      do_somthing with _Input_ to produce _Output_
      return _Output_
```



function มีส่วนสำคัญทั้งหมด 4 ส่วน

```
 1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name(): (ขาดไม่ได้)
 2. กำหนดตัวแปรที่จะเป็น input Input (ขาดได้)
 3. ส่วนประมวลผล do_something with Input to get Output (ขาดไม่ได้)
 4. ส่วน output return Output(ขาดได้)

 ```
เราใช้ เว้นวรรค (indent) เพื่อบอกขอบเขตของ code


input มีกี่ตัวก็ได้

สร้างฟังก์ชั่น

In [ ]:
def print_name(name,surname,ID):
    st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
    return st

การใช้ฟังก์ชั่น

In [ ]:
print_name('ชนกานต์','พูลผล','623021046-7')

'ชื่อ ชนกานต์ นามสกุล พูลผล ID 623021046-7'

In [ ]:
output_string=print_name('ชนกานต์','พูลผล','623021046-7')
print(output_string)

ชื่อ ชนกานต์ นามสกุล พูลผล ID 623021046-7


ฟังชันก์ไม่จำเป็นต้องมี output

In [ ]:
def print_name2(name,surname,ID):
    st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
    print (st)


In [ ]:
print_name2('ชนกานต์','พูลผล','623021046-7')

ชื่อ ชนกานต์ นามสกุล พูลผล ID 623021046-7


In [ ]:
op2 = print_name2('ชนกานต์','พูลผล','623021046-7')


ชื่อ ชนกานต์ นามสกุล พูลผล ID 623021046-7


In [ ]:
print(op2)

None


ฟังชันก์ไม่จำเป็นต้องมี input

In [ ]:
def pi():
  return 3.14159265359

In [ ]:
#คำนวณพื้นที่วงกลมที่มีขนาดเส้นผ่านศูนย์กลางเท่ากับ3
pi()*(1.5**2)

7.0685834705775

In [ ]:
def print_my_name( ):
      print( ' ชนกานต์  พูลผล  623021046-7 ' )

In [ ]:
print_my_name( )

 ชนกานต์  พูลผล  623021046-7 


1. input ของ function ใน python มีสองแบบ input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default)
2. เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_2lines_default(name,surname,ID,grade= 'F' ):
      st = f' ชื่อ {name} นามสกุล {surname} isyl {ID}'
      print(st)
      st2=f'เกรดวิชา Multivariate >>> {grade}'
      print(st2)

In [ ]:
print_2lines_default('ชนกานต์' , 'พูลผล' , '623021046-7' )

 ชื่อ ชนกานต์ นามสกุล พูลผล isyl 623021046-7
เกรดวิชา Multivariate >>> F


In [ ]:
print_2lines_default('ชนกานต์' , 'พูลผล' , '623021046-7', 'A' )

 ชื่อ ชนกานต์ นามสกุล พูลผล isyl 623021046-7
เกรดวิชา Multivariate >>> A


เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรอื่นของฟังก์ชั่นช่วยได้


In [ ]:
print_name2(name='ชนกานต์', surname='พูลผล', ID='623021046-7')

ชื่อ ชนกานต์ นามสกุล พูลผล ID 623021046-7




```
HW3 ให้เขียน function คำนวณจำนวนวินาทีจาก เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'
และ print ให้สวยงาม
```



ANSWER

In [ ]:
def function_time(time):
    st = time.split('-')
    ans = int(st[0]) * 3600 + int(st[1]) * 60 + int(st[2]) 
    print(f'คำนวณจำนวนวินาทีจาก {time} จะเท่ากับ {ans} วินาที')

In [ ]:
function_time('14-15-31')

คำนวณจำนวนวินาทีจาก 14-15-31 จะเท่ากับ 51331 วินาที


In [ ]:
function_time('13-00-01')


คำนวณจำนวนวินาทีจาก 13-00-01 จะเท่ากับ 46801 วินาที


In [ ]:
function_time('15-49-44')

คำนวณจำนวนวินาทีจาก 15-49-44 จะเท่ากับ 56984 วินาที


In [ ]:
function_time('00-00-16')

คำนวณจำนวนวินาทีจาก 00-00-16 จะเท่ากับ 16 วินาที



Numpy -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num+py -> Number-Numerical + python

การใช้ package
1. ``` import ``` ``` ชื่อpackage ``` #เรียกใช้ package
2.``` ชื่อpackage ``` ``` ชื่อฟังก์ชั่น ``` #เรียกใช้ function




In [4]:
import numpy

สร้าง array (nump array)

In [5]:
mat_ex1=numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [6]:
mat_ex1[1,1] #[แถว,หลัก]

0.1

ไม่มี numpy array

In [7]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


list เป็นการชี้

In [9]:
list_ex1[1][1]

0.1

In [10]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix Operation

data 2 แบบ -> matrix(2D array), scalar(ตัวเลขค่าคงที่)

In [13]:
mat_ex1=numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2=numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


บวกและลบ mat ตัวเลขในตำแหน่งเดียวกันเอามาบวกกัน


```
หน้าตาของmat ต้องเหมือนกัน
```



In [14]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)


[[10.4  6.   9. ]
 [18.2  0.2  0.6]]
[[0. 0. 0.]
 [0. 0. 0.]]


การตรวจสอบขนาดของ mat 

In [15]:
mat_ex3.shape

(2, 3)

shape บอกขนาด ต่างจากลิสต์ 

In [20]:
mat_ex3.shape[0]

2



```
การใช้งานเหมือนลิสต์
```




การคูณ mat แถวคูณหลัก
แถว 1 คูณ หลัก 2  

In [21]:
print(mat_ex1)
print(mat_ex2)


[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [23]:
mat_ex1*mat_ex2

array([[2.704e+01, 9.000e+00, 2.025e+01],
       [8.281e+01, 1.000e-02, 9.000e-02]])

##การคูณmat สิ่งที่จะทำคูณmatได้คือ แถวคุณหลัก 
(หลักของmat ตัวข้างหน้า ต้องเท่ากับแถวของmatrixข้างหลัง)

((ooo,X),(X,จจจ))= (ooo,จจจ)

In [31]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)


Transpose กลับแถวเป็นหลัก กลับ หลักเป็นแถว




```
mat.T
```





In [32]:
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)


In [33]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]
(3, 2)


In [34]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2)


array([[56.29, 48.97],
       [48.97, 82.91]])

In [37]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3)

array([[109.85,  16.51,  26.13],
       [ 16.51,   9.01,  13.53],
       [ 26.13,  13.53,  20.34]])

### HW

HW 4 อธิบายการหา Determinant และ inverse matric (รูปและคำอธิบาย)